package graduation.hnust.simplebook.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACCOUNT_REMIND".
 */
public class AccountRemind {

    private Long id;
    private Long userId;
    private Long bookId;
    private Integer type;
    private Integer status;
    private String name;
    private java.util.Date endTime;
    private java.util.Date remindTime;
    private Integer repeatTime;
    private Integer amount;
    private Boolean isAutoMark;
    private Integer consumeType;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    public AccountRemind() {
    }

    public AccountRemind(Long id) {
        this.id = id;
    }

    public AccountRemind(Long id, Long userId, Long bookId, Integer type, Integer status, String name, java.util.Date endTime, java.util.Date remindTime, Integer repeatTime, Integer amount, Boolean isAutoMark, Integer consumeType, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.userId = userId;
        this.bookId = bookId;
        this.type = type;
        this.status = status;
        this.name = name;
        this.endTime = endTime;
        this.remindTime = remindTime;
        this.repeatTime = repeatTime;
        this.amount = amount;
        this.isAutoMark = isAutoMark;
        this.consumeType = consumeType;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getBookId() {
        return bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public java.util.Date getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(java.util.Date remindTime) {
        this.remindTime = remindTime;
    }

    public Integer getRepeatTime() {
        return repeatTime;
    }

    public void setRepeatTime(Integer repeatTime) {
        this.repeatTime = repeatTime;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Boolean getIsAutoMark() {
        return isAutoMark;
    }

    public void setIsAutoMark(Boolean isAutoMark) {
        this.isAutoMark = isAutoMark;
    }

    public Integer getConsumeType() {
        return consumeType;
    }

    public void setConsumeType(Integer consumeType) {
        this.consumeType = consumeType;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
