package graduation.hnust.simplebook.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "BOOK".
 */
public class Book implements Serializable {

    private Long id;
    private Long userId;
    private Integer type;
    private String name;
    private Boolean isDefault;
    private Integer status;
    private Integer budget;
    private java.util.Date settlementTime;
    private Boolean idRemind;
    private String color;
    private Integer storeType;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, Long userId, Integer type, String name, Boolean isDefault, Integer status, Integer budget, java.util.Date settlementTime, Boolean idRemind, String color, Integer storeType, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.name = name;
        this.isDefault = isDefault;
        this.status = status;
        this.budget = budget;
        this.settlementTime = settlementTime;
        this.idRemind = idRemind;
        this.color = color;
        this.storeType = storeType;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getBudget() {
        return budget;
    }

    public void setBudget(Integer budget) {
        this.budget = budget;
    }

    public java.util.Date getSettlementTime() {
        return settlementTime;
    }

    public void setSettlementTime(java.util.Date settlementTime) {
        this.settlementTime = settlementTime;
    }

    public Boolean getIdRemind() {
        return idRemind;
    }

    public void setIdRemind(Boolean idRemind) {
        this.idRemind = idRemind;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getStoreType() {
        return storeType;
    }

    public void setStoreType(Integer storeType) {
        this.storeType = storeType;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
