package graduation.hnust.simplebook.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QQINFO_MODEL".
 */
public class QQInfoModel {

    private Long id;
    private Long userId;
    private String ret;
    private String msg;
    private String isLost;
    private String nickname;
    private String gender;
    private String province;
    private String city;
    private String year;
    private String figureUrl;
    private String figureUrl1;
    private String figureUrl2;
    private String figureUrlQq1;
    private String figureUrlQq2;
    private String isYellowVip;
    private String vip;
    private String yellowVipLevel;
    private String level;
    private String isYellowYearVip;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    public QQInfoModel() {
    }

    public QQInfoModel(Long id) {
        this.id = id;
    }

    public QQInfoModel(Long id, Long userId, String ret, String msg, String isLost, String nickname, String gender, String province, String city, String year, String figureUrl, String figureUrl1, String figureUrl2, String figureUrlQq1, String figureUrlQq2, String isYellowVip, String vip, String yellowVipLevel, String level, String isYellowYearVip, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.userId = userId;
        this.ret = ret;
        this.msg = msg;
        this.isLost = isLost;
        this.nickname = nickname;
        this.gender = gender;
        this.province = province;
        this.city = city;
        this.year = year;
        this.figureUrl = figureUrl;
        this.figureUrl1 = figureUrl1;
        this.figureUrl2 = figureUrl2;
        this.figureUrlQq1 = figureUrlQq1;
        this.figureUrlQq2 = figureUrlQq2;
        this.isYellowVip = isYellowVip;
        this.vip = vip;
        this.yellowVipLevel = yellowVipLevel;
        this.level = level;
        this.isYellowYearVip = isYellowYearVip;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getRet() {
        return ret;
    }

    public void setRet(String ret) {
        this.ret = ret;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getIsLost() {
        return isLost;
    }

    public void setIsLost(String isLost) {
        this.isLost = isLost;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getFigureUrl() {
        return figureUrl;
    }

    public void setFigureUrl(String figureUrl) {
        this.figureUrl = figureUrl;
    }

    public String getFigureUrl1() {
        return figureUrl1;
    }

    public void setFigureUrl1(String figureUrl1) {
        this.figureUrl1 = figureUrl1;
    }

    public String getFigureUrl2() {
        return figureUrl2;
    }

    public void setFigureUrl2(String figureUrl2) {
        this.figureUrl2 = figureUrl2;
    }

    public String getFigureUrlQq1() {
        return figureUrlQq1;
    }

    public void setFigureUrlQq1(String figureUrlQq1) {
        this.figureUrlQq1 = figureUrlQq1;
    }

    public String getFigureUrlQq2() {
        return figureUrlQq2;
    }

    public void setFigureUrlQq2(String figureUrlQq2) {
        this.figureUrlQq2 = figureUrlQq2;
    }

    public String getIsYellowVip() {
        return isYellowVip;
    }

    public void setIsYellowVip(String isYellowVip) {
        this.isYellowVip = isYellowVip;
    }

    public String getVip() {
        return vip;
    }

    public void setVip(String vip) {
        this.vip = vip;
    }

    public String getYellowVipLevel() {
        return yellowVipLevel;
    }

    public void setYellowVipLevel(String yellowVipLevel) {
        this.yellowVipLevel = yellowVipLevel;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getIsYellowYearVip() {
        return isYellowYearVip;
    }

    public void setIsYellowYearVip(String isYellowYearVip) {
        this.isYellowYearVip = isYellowYearVip;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
