package graduation.hnust.simplebook.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import graduation.hnust.simplebook.model.User;
import graduation.hnust.simplebook.model.QQInfoModel;
import graduation.hnust.simplebook.model.QQTokenModel;
import graduation.hnust.simplebook.model.AccountRemind;
import graduation.hnust.simplebook.model.Book;
import graduation.hnust.simplebook.model.ConsumeType;
import graduation.hnust.simplebook.model.FeedBack;
import graduation.hnust.simplebook.model.Item;

import graduation.hnust.simplebook.greendao.UserDao;
import graduation.hnust.simplebook.greendao.QQInfoModelDao;
import graduation.hnust.simplebook.greendao.QQTokenModelDao;
import graduation.hnust.simplebook.greendao.AccountRemindDao;
import graduation.hnust.simplebook.greendao.BookDao;
import graduation.hnust.simplebook.greendao.ConsumeTypeDao;
import graduation.hnust.simplebook.greendao.FeedBackDao;
import graduation.hnust.simplebook.greendao.ItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig qQInfoModelDaoConfig;
    private final DaoConfig qQTokenModelDaoConfig;
    private final DaoConfig accountRemindDaoConfig;
    private final DaoConfig bookDaoConfig;
    private final DaoConfig consumeTypeDaoConfig;
    private final DaoConfig feedBackDaoConfig;
    private final DaoConfig itemDaoConfig;

    private final UserDao userDao;
    private final QQInfoModelDao qQInfoModelDao;
    private final QQTokenModelDao qQTokenModelDao;
    private final AccountRemindDao accountRemindDao;
    private final BookDao bookDao;
    private final ConsumeTypeDao consumeTypeDao;
    private final FeedBackDao feedBackDao;
    private final ItemDao itemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        qQInfoModelDaoConfig = daoConfigMap.get(QQInfoModelDao.class).clone();
        qQInfoModelDaoConfig.initIdentityScope(type);

        qQTokenModelDaoConfig = daoConfigMap.get(QQTokenModelDao.class).clone();
        qQTokenModelDaoConfig.initIdentityScope(type);

        accountRemindDaoConfig = daoConfigMap.get(AccountRemindDao.class).clone();
        accountRemindDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        consumeTypeDaoConfig = daoConfigMap.get(ConsumeTypeDao.class).clone();
        consumeTypeDaoConfig.initIdentityScope(type);

        feedBackDaoConfig = daoConfigMap.get(FeedBackDao.class).clone();
        feedBackDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        qQInfoModelDao = new QQInfoModelDao(qQInfoModelDaoConfig, this);
        qQTokenModelDao = new QQTokenModelDao(qQTokenModelDaoConfig, this);
        accountRemindDao = new AccountRemindDao(accountRemindDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);
        consumeTypeDao = new ConsumeTypeDao(consumeTypeDaoConfig, this);
        feedBackDao = new FeedBackDao(feedBackDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(QQInfoModel.class, qQInfoModelDao);
        registerDao(QQTokenModel.class, qQTokenModelDao);
        registerDao(AccountRemind.class, accountRemindDao);
        registerDao(Book.class, bookDao);
        registerDao(ConsumeType.class, consumeTypeDao);
        registerDao(FeedBack.class, feedBackDao);
        registerDao(Item.class, itemDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        qQInfoModelDaoConfig.getIdentityScope().clear();
        qQTokenModelDaoConfig.getIdentityScope().clear();
        accountRemindDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
        consumeTypeDaoConfig.getIdentityScope().clear();
        feedBackDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public QQInfoModelDao getQQInfoModelDao() {
        return qQInfoModelDao;
    }

    public QQTokenModelDao getQQTokenModelDao() {
        return qQTokenModelDao;
    }

    public AccountRemindDao getAccountRemindDao() {
        return accountRemindDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public ConsumeTypeDao getConsumeTypeDao() {
        return consumeTypeDao;
    }

    public FeedBackDao getFeedBackDao() {
        return feedBackDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

}
